name: ai-diagnosis

channels:
  - defaults

dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - libffi=3.4.4
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - annotated-types==0.6.0
      - attrs==23.2.0
      - bcrypt==4.1.2
      - boto3==1.34.74
      - botocore==1.34.74
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cryptography==42.0.5
      - edge-logger==0.0.11
      - future==1.0.0
      - grpcio==1.62.1
      - idna==3.6
      - influxdb==5.3.1
      - ipywidgets==8.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyterlab-widgets==3.0.10
      - llvmlite==0.42.0
      - lxml==5.2.0
      - ming==0.13.0
      - msgpack==1.0.8
      - nats-py==2.6.0
      - ncclient==0.6.15
      - netmiko==4.2.0
      - ntc-templates==4.4.0
      - numba==0.59.1
      - numpy==1.24.3
      - pandas==2.2.1
      - paramiko==3.3.1
      - plotly==5.20.0
      - protobuf==5.26.1
      - pycparser==2.22
      - pydantic==2.5.1
      - pydantic-core==2.14.3
      - pymongo==3.13.0
      - pynacl==1.5.0
      - pyserial==3.5
      - python-dateutil==2.9.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.34.0
      - requests==2.31.0
      - rpds-py==0.18.0
      - s3transfer==0.10.1
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - scp==0.14.5
      - six==1.16.0
      - stumpy==1.12.0
      - tenacity==8.2.3
      - textfsm==1.1.3
      - threadpoolctl==3.4.0
      - typing-extensions==4.10.0
      - urllib3==2.2.1
      - widgetsnbextension==4.0.10
      - python-dotenv==1.0.1
      - jinja2==3.1.3
      - nbformat==5.10.4
      - nltk==3.8.1
      - numexpr==2.10.0
      - matplotlib==3.8.4
      - networkx==3.2.1
      - itables==2.0.0
      - mplcursors==0.5.3
      - ipykernel==6.29.4
      - openai==1.23.2

